"""Build complete Q4 source listings without changing executable modules.

The AST dependency closure includes local imports in optional branches, so the
compact entry point and its joint/legacy comparisons remain reviewable. Only
the display copies replace Unicode symbols with LaTeX listing escapes. Original
byte hashes, dependency edges, and the exact transformations are recorded.
"""
from __future__ import annotations

import ast
import hashlib
import json
from pathlib import Path


Q4 = Path(__file__).resolve().parents[1]
SRC = Q4 / "src"
PAPER = Q4.parent / "paper"
OUTPUT = Q4 / "out" / "paper_q4" / "source_display"
ROOTS = {
    "compact": "src/p4_compact.py",
    "joint_comparison": "src/p4_search.py",
    "legacy_comparison": "src/p4_robot.py",
    "entry_point": "src/p4_run.py",
    "entry_wrapper": "scripts/run_p4.py",
    "paper_experiments": "run_paper_q4.py",
    "paper_tables": "make_paper_tables.py",
    "paper_figures": "scripts/make_paper_figures.py",
}
START, END = "(*@", "@*)"
MATH_GLYPHS = {
    "°": r"{}^{\circ}", "±": r"\pm", "²": r"{}^2", "·": r"\cdot",
    "×": r"\times", "÷": r"\div", "Δ": r"\Delta", "Σ": r"\Sigma",
    "ε": r"\epsilon", "θ": r"\theta", "λ": r"\lambda", "π": r"\pi",
    "ρ": r"\rho", "φ": r"\phi", "ᵢ": r"{}_i", "⁺": r"{}^{+}",
    "⁻": r"{}^{-}", "←": r"\leftarrow", "→": r"\rightarrow",
    "↷": r"\curvearrowright", "⇒": r"\Rightarrow", "∈": r"\in",
    "−": "-", "∓": r"\mp", "√": r"\surd", "∝": r"\propto",
    "∞": r"\infty", "∠": r"\angle", "∩": r"\cap", "≈": r"\approx",
    "≠": r"\ne", "≡": r"\equiv", "≤": r"\le", "≥": r"\ge",
    "≳": r"\gtrsim", "⏹": r"\blacksquare", "■": r"\blacksquare",
    "▲": r"\blacktriangle", "★": r"\star", "⟨": r"\langle",
    "⟩": r"\rangle", "⟺": r"\Longleftrightarrow", "…": r"\ldots",
}
TEXT_GLYPHS = {
    "§": r"\S{}", "–": r"\textendash{}", "—": r"\textemdash{}",
    "⚠": r"\textbf{[!]}",
}
for digit, glyph in enumerate("①②③④⑤⑥⑦⑧⑨⑩", start=1):
    TEXT_GLYPHS[glyph] = r"\textcircled{" + str(digit) + "}"


def local_imports(relative_path: str) -> list[str]:
    """Find imports resolvable to a Python file in this Q4 source directory."""
    tree = ast.parse((Q4 / relative_path).read_text(encoding="utf-8-sig"))
    found = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            names = [alias.name for alias in node.names]
        elif isinstance(node, ast.ImportFrom) and node.module:
            names = [node.module]
        else:
            continue
        for name in names:
            module = name.split(".")[0]
            candidate = SRC / (module + ".py")
            if candidate.is_file():
                found.add(candidate.relative_to(Q4).as_posix())
    return sorted(found)


def dependency_closure(root: str, edges: dict[str, list[str]]) -> set[str]:
    visited, pending = set(), [root]
    while pending:
        relative = pending.pop()
        if relative in visited:
            continue
        visited.add(relative)
        if relative not in edges:
            edges[relative] = local_imports(relative)
        pending.extend(edges[relative])
    return visited


def display_copy(raw: str) -> tuple[str, dict[str, int]]:
    if START in raw or END in raw:
        raise ValueError("A source contains the chosen listings escape markers")
    output, counts = [], {}
    for glyph in raw:
        if glyph in MATH_GLYPHS:
            replacement = START + r"\ensuremath{" + MATH_GLYPHS[glyph] + "}" + END
        elif glyph in TEXT_GLYPHS:
            replacement = START + TEXT_GLYPHS[glyph] + END
        elif glyph == "\ufe0f":
            replacement = ""  # Emoji presentation selector has no printed glyph.
        else:
            replacement = glyph
        if replacement != glyph:
            counts[glyph] = counts.get(glyph, 0) + 1
        output.append(replacement)
    return "".join(output), counts


def main() -> None:
    edges: dict[str, list[str]] = {}
    groups = {label: dependency_closure(root, edges) for label, root in ROOTS.items()}
    files = set().union(*groups.values())
    # Dependencies precede their users; the second guard handles import cycles.
    ordered, visited, active = [], set(), set()

    def visit(name: str) -> None:
        if name in visited or name in active:
            return
        active.add(name)
        for dependency in edges[name]:
            visit(dependency)
        active.remove(name)
        visited.add(name)
        ordered.append(name)

    for name in sorted(files):
        visit(name)
    OUTPUT.mkdir(parents=True, exist_ok=True)
    parts = [
        "% Generated by Q4/scripts/make_paper_source.py; do not edit.\n",
        "% Complete original sources; only Unicode display escapes differ.\n",
        "\\begingroup\n",
        r"\lstset{columns=fullflexible,keepspaces=true,breaklines=true,breakatwhitespace=false,commentstyle=\color[rgb]{0.12,0.34,0.24},stringstyle=\color[rgb]{0.15,0.30,0.35},keywordstyle=\color[rgb]{0.13,0.23,0.43}}" + "\n",
        "\\noindent 以下逐文件列出问题四默认策略、上一版联合策略及原格网策略的本地依赖源码、运行入口与论文实验、制表和绘图程序。"
        "为避免字体缺字，仅在本排版副本中将数学符号转换为等义的 LaTeX 命令，"
        "告警符号显示为 [!]，省略无可见字形的表情呈现选择符；可执行源码未作修改。"
        "逐文件原始字节 SHA256、依赖关系及转换数量保存在支撑材料的源码清单中。\\par\n",
    ]
    records = []
    for name in ordered:
        original_bytes = (Q4 / name).read_bytes()
        # Keep display copies stable when a checkout uses Windows line endings;
        # provenance hashes below still describe the original source bytes.
        raw = original_bytes.decode("utf-8-sig").replace("\r\n", "\n").replace("\r", "\n")
        display, counts = display_copy(raw)
        target = OUTPUT / (name + ".listing.txt")
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(display, encoding="utf-8", newline="\n")
        digest = hashlib.sha256(original_bytes).hexdigest()
        title = ("Q4/" + name).replace("_", r"\_")
        parts += [
            r"\subsection{\texttt{" + title + "}}\n",
            "% Original byte SHA256 " + digest + "\n",
            r"\begin{lstlisting}[language=python,escapeinside={(*@}{@*)}]" + "\n",
            display.rstrip("\r\n") + "\n",
            r"\end{lstlisting}" + "\n",
        ]
        records.append({
            "path": "Q4/" + name,
            "sha256": digest,
            "bytes": len(original_bytes),
            "lines": len(raw.splitlines()),
            "included_by": [label for label, closure in groups.items() if name in closure],
            "local_imports": ["Q4/" + dependency for dependency in edges[name]],
            "display_path": target.relative_to(Q4).as_posix(),
            "display_sha256": hashlib.sha256(target.read_bytes()).hexdigest(),
            "display_replacements": counts,
        })
    parts.append("\\endgroup\n")
    tex_path = PAPER / "sections" / "q4-source-listings.tex"
    tex_path.write_text("".join(parts), encoding="utf-8", newline="\n")
    manifest = {
        "description": "Complete AST local-import closure, including optional local imports; executable originals unchanged.",
        "roots": ROOTS,
        "file_count": len(records),
        "total_source_lines": sum(record["lines"] for record in records),
        "listing_path": tex_path.relative_to(Q4.parent).as_posix(),
        "math_display_map": MATH_GLYPHS,
        "text_display_map": TEXT_GLYPHS,
        "omitted_display_characters": ["U+FE0F"],
        "files": records,
    }
    (OUTPUT / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8", newline="\n",
    )
    # Re-read originals after writing: producing display copies must not alter them.
    for record in records:
        relative = record["path"].removeprefix("Q4/")
        assert hashlib.sha256((Q4 / relative).read_bytes()).hexdigest() == record["sha256"]
    print(json.dumps({"files": len(records), "lines": manifest["total_source_lines"],
                      "listing": str(tex_path), "manifest": str(OUTPUT / "manifest.json")},
                     ensure_ascii=False))


if __name__ == "__main__":
    main()
